ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.postgres.amqp.SerializationKt.configureSerialization
      - com.postgres.amqp.RequestValidationKt.configureRequestValidation
      - com.postgres.amqp.ExposedKt.configureExposed
      - com.postgres.amqp.RabbitmqKt.configureRabbitmq
      - com.postgres.amqp.RoutingKt.configureRouting      
rabbitmq:
  uri: "amqp://guest:guest@localhost:5672"
  name: "ktor-consumer"
